name: cobinHood
channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.22.0=py36_0
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- cffi=1.11.2=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py_1
- cryptography=2.1.4=py36_0
- flask=0.12.2=py36_0
- idna=2.6=py36_1
- itsdangerous=0.24=py_2
- jinja2=2.10=py36_0
- markupsafe=1.0=py36_0
- openssl=1.0.2n=vc14_0
- pip=9.0.1=py36_1
- pycparser=2.18=py36_0
- pyopenssl=17.2.0=py36_0
- pysocks=1.6.8=py36_1
- python=3.6.4=0
- requests=2.18.4=py36_1
- setuptools=38.4.0=py36_0
- six=1.11.0=py36_1
- urllib3=1.22=py36_0
- vs2015_runtime=14.0.25420=0
- werkzeug=0.14.1=py_0
- wheel=0.30.0=py36_2
- win_inet_pton=1.0.1=py36_1
- wincertstore=0.2=py36_0
- pip:
  - win-inet-pton==1.0.1

